import React from 'react'
import './Content.css'

function Content() {
  return (

      <div className="Content">
        <p>
        TESTETESTETESTETESTETESTETESTETESTETESTETESTETESTE
        TESTETESTETESTETESTETESTETESTETESTETESTETESTE
        TESTETESTETESTETESTETESTETESTETESTETESTETESTETESTETESTE
        TESTETESTETESTETESTETESTETESTETESTETESTETESTETESTETESTETESTE
        TESTETESTETESTETESTETESTETESTETESTETESTETESTE
        TESTE
        </p>
      </div>

  )
}

export default Content;
